import { ElementRef, EventEmitter } from '@angular/core';
export declare class PinchZoomComponent {
    private elementRef;
    i: number;
    _id: any;
    element: any;
    content: any;
    elementPosition: any;
    parentElement: any;
    eventType: any;
    scale: number;
    initialScale: number;
    startX: number;
    startY: number;
    startClientX: number;
    startClientY: number;
    moveX: any;
    moveY: any;
    initialMoveX: any;
    initialMoveY: any;
    moveXC: number;
    moveYC: number;
    distance: number;
    initialDistance: number;
    draggingMode: boolean;
    doubleTapTimeout: any;
    lastTap: number;
    containerHeight: string;
    transitionDuration: number;
    doubleTap: boolean;
    zoomButton: boolean;
    linearHorizontalSwipe: boolean;
    linearVerticalSwipe: boolean;
    autoZoomOut: boolean;
    id: any;
    events: EventEmitter<any>;
    hostDisplay: string;
    hostOverflow: string;
    hostHeight: string;
    contentElement: ElementRef;
    readonly isMobile: boolean;
    readonly isDragging: boolean;
    constructor(elementRef: ElementRef);
    ngOnInit(): void;
    onMouseEnter(event: MouseEvent): void;
    onMouseMove(event: MouseEvent): void;
    onMouseUp(event: MouseEvent): void;
    onResize(event: Event): void;
    touchstartHandler(event: any): void;
    touchmoveHandler(event: any): void;
    touchendHandler(event: any): void;
    handleSwipe(event: any): void;
    handlePinch(event: any): void;
    handleLinearSwipe(event: any): void;
    detectSwipe(touches: any): boolean;
    detectLinearSwipe(touches: TouchList): boolean;
    getLinearSwipeType(event: any): string;
    getDistance(touches: any): number;
    getImageHeight(): any;
    getImageWidth(): any;
    setBasicStyles(): void;
    setImageWidth(): void;
    transformElement(duration?: any): void;
    doubleTapDetection(): boolean;
    toggleZoom(event?: any): void;
    resetScale(): void;
    updateInitialValues(): void;
    centeringImage(): boolean;
    alignImage(): void;
    transitionYRestriction(): void;
    transitionXRestriction(): void;
    getElementPosition(): void;
    setMoveX(value: number, transitionDuration?: number): void;
    setMoveY(value: number, transitionDuration?: number): void;
}
